# Generated by Django 4.2.5 on 2023-12-25 01:24

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0008_alter_intervenciones_type_talarazaintervencion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis_pindo', '0002_delete_talarazaintervenciongis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalarazaIntervenciongis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5349)),
                ('geom_4326', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('intervencion_gis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talaraza_intervencion_gis', to='intervenciones.intervenciones')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_talaraza_intervencion_gis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
